import type { Component } from 'vue';
import {
  Cpu,
  Landmark,
  HeartPulse,
  ShoppingBag,
  Factory,
  Truck,
  Briefcase,
  GraduationCap,
  UtensilsCrossed,
  Building2,
  Radio,
  Zap,
  Palmtree,
  Wheat,
  Scale,
  ShieldCheck,
  Car,
  Fuel,
  Compass,
  FileSpreadsheet,
  Globe
} from 'lucide-vue-next';

export interface SectorEconomico {
  id: string;
  codigo: string;
  nombre: string;
  icono: string;
  color: string; // Tailwind text & background classes
  dotColor: string; // dot color for AppSelect
  descripcion?: string;
  activo: boolean;
}

export const MAPA_ICONOS_SECTOR: Record<string, Component> = {
  Cpu,
  Landmark,
  HeartPulse,
  ShoppingBag,
  Factory,
  Truck,
  Briefcase,
  GraduationCap,
  UtensilsCrossed,
  Building2,
  Radio,
  Zap,
  Palmtree,
  Wheat,
  Scale,
  ShieldCheck,
  Car,
  Fuel,
  Compass,
  FileSpreadsheet,
  Globe,
};

export const LISTA_ICONOS_DISPONIBLES: Array<{ id: string; label: string; componente: Component }> = [
  { id: 'Cpu', label: 'Tecnología / CPU', componente: Cpu },
  { id: 'Landmark', label: 'Finanzas / Banco', componente: Landmark },
  { id: 'HeartPulse', label: 'Salud / Médico', componente: HeartPulse },
  { id: 'ShoppingBag', label: 'Retail / Comercio', componente: ShoppingBag },
  { id: 'Factory', label: 'Industria / Fábrica', componente: Factory },
  { id: 'Truck', label: 'Logística / Transporte', componente: Truck },
  { id: 'Briefcase', label: 'Servicios Profesionales', componente: Briefcase },
  { id: 'GraduationCap', label: 'Educación / Academia', componente: GraduationCap },
  { id: 'UtensilsCrossed', label: 'Alimentos / Gastronomía', componente: UtensilsCrossed },
  { id: 'Building2', label: 'Construcción / Inmobiliaria', componente: Building2 },
  { id: 'Radio', label: 'Telecomunicaciones', componente: Radio },
  { id: 'Zap', label: 'Energía / Eléctrico', componente: Zap },
  { id: 'Palmtree', label: 'Turismo / Hotelería', componente: Palmtree },
  { id: 'Wheat', label: 'Agroindustria / Campo', componente: Wheat },
  { id: 'Scale', label: 'Legal / Jurídico', componente: Scale },
  { id: 'ShieldCheck', label: 'Seguridad / Auditoría', componente: ShieldCheck },
  { id: 'Car', label: 'Automotriz / Vehículos', componente: Car },
  { id: 'Fuel', label: 'Combustibles / Gas', componente: Fuel },
  { id: 'Compass', label: 'Consultoría / Estrategia', componente: Compass },
  { id: 'Globe', label: 'Internacional / Multilatina', componente: Globe },
];

export const PALETA_COLORES_SECTOR = [
  { id: 'indigo', label: 'Índigo', color: 'text-indigo-400 bg-indigo-500/10 border-indigo-500/20', dotColor: 'bg-indigo-400' },
  { id: 'emerald', label: 'Esmeralda', color: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20', dotColor: 'bg-emerald-400' },
  { id: 'rose', label: 'Rosa / Carmín', color: 'text-rose-400 bg-rose-500/10 border-rose-500/20', dotColor: 'bg-rose-400' },
  { id: 'amber', label: 'Ámbar / Naranja', color: 'text-amber-400 bg-amber-500/10 border-amber-500/20', dotColor: 'bg-amber-400' },
  { id: 'sky', label: 'Cielo / Azul', color: 'text-sky-400 bg-sky-500/10 border-sky-500/20', dotColor: 'bg-sky-400' },
  { id: 'purple', label: 'Púrpura / Violeta', color: 'text-purple-400 bg-purple-500/10 border-purple-500/20', dotColor: 'bg-purple-400' },
  { id: 'teal', label: 'Verde Azulado', color: 'text-teal-400 bg-teal-500/10 border-teal-500/20', dotColor: 'bg-teal-400' },
  { id: 'zinc', label: 'Neutro / Zinc', color: 'text-zinc-400 bg-zinc-500/10 border-zinc-500/20', dotColor: 'bg-zinc-400' },
];

export const SECTORES_INICIALES: SectorEconomico[] = [
  {
    id: 'sec-tecnologia',
    codigo: 'TEC',
    nombre: 'Tecnología & Cloud',
    icono: 'Cpu',
    color: 'text-indigo-400 bg-indigo-500/10 border-indigo-500/20',
    dotColor: 'bg-indigo-400',
    descripcion: 'Software, infraestructura en la nube, SaaS, ciberseguridad y servicios de TI',
    activo: true,
  },
  {
    id: 'sec-finanzas',
    codigo: 'FIN',
    nombre: 'Finanzas & Inversiones',
    icono: 'Landmark',
    color: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20',
    dotColor: 'bg-emerald-400',
    descripcion: 'Banca múltiple, fondos de inversión, cooperativas, fintech y aseguradoras',
    activo: true,
  },
  {
    id: 'sec-salud',
    codigo: 'SAL',
    nombre: 'Salud & Redes Médicas',
    icono: 'HeartPulse',
    color: 'text-rose-400 bg-rose-500/10 border-rose-500/20',
    dotColor: 'bg-rose-400',
    descripcion: 'Clínicas, centros de diagnóstico, farmacéuticas y laboratorios clínicos',
    activo: true,
  },
  {
    id: 'sec-retail',
    codigo: 'RET',
    nombre: 'Retail & Comercio',
    icono: 'ShoppingBag',
    color: 'text-amber-400 bg-amber-500/10 border-amber-500/20',
    dotColor: 'bg-amber-400',
    descripcion: 'Cadenas de supermercados, tiendas por departamentos, distribuidores y e-commerce',
    activo: true,
  },
  {
    id: 'sec-manufactura',
    codigo: 'MAN',
    nombre: 'Manufactura & Industria',
    icono: 'Factory',
    color: 'text-purple-400 bg-purple-500/10 border-purple-500/20',
    dotColor: 'bg-purple-400',
    descripcion: 'Zonas francas, plantas de producción industrial, plásticos y manufactura ligera',
    activo: true,
  },
  {
    id: 'sec-logistica',
    codigo: 'LOG',
    nombre: 'Logística & Aduanas',
    icono: 'Truck',
    color: 'text-sky-400 bg-sky-500/10 border-sky-500/20',
    dotColor: 'bg-sky-400',
    descripcion: 'Transporte de carga, puertos, depósitos fiscales, couriers y agentes aduanales',
    activo: true,
  },
  {
    id: 'sec-servicios',
    codigo: 'SER',
    nombre: 'Servicios Profesionales',
    icono: 'Briefcase',
    color: 'text-teal-400 bg-teal-500/10 border-teal-500/20',
    dotColor: 'bg-teal-400',
    descripcion: 'Firmas de auditoría, asesoría fiscal, despachos legales y consultoría de negocios',
    activo: true,
  },
  {
    id: 'sec-turismo',
    codigo: 'TUR',
    nombre: 'Turismo & Hotelería',
    icono: 'Palmtree',
    color: 'text-amber-400 bg-amber-500/10 border-amber-500/20',
    dotColor: 'bg-amber-400',
    descripcion: 'Cadenas hoteleras, resorts, touroperadores y servicios turísticos receptivos',
    activo: true,
  },
  {
    id: 'sec-construccion',
    codigo: 'CON',
    nombre: 'Construcción & Inmobiliaria',
    icono: 'Building2',
    color: 'text-zinc-400 bg-zinc-500/10 border-zinc-500/20',
    dotColor: 'bg-zinc-400',
    descripcion: 'Desarrolladoras residenciales, contratistas de obras civiles e ingeniería estructural',
    activo: true,
  },
  {
    id: 'sec-educacion',
    codigo: 'EDU',
    nombre: 'Educación & Formación',
    icono: 'GraduationCap',
    color: 'text-indigo-400 bg-indigo-500/10 border-indigo-500/20',
    dotColor: 'bg-indigo-400',
    descripcion: 'Universidades, institutos tecnológicos, colegios bilingües y centros de capacitación',
    activo: true,
  },
];
